name = "Sickos"
author = "brooswit"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e20bb0a377ca3a7b6fc2d36c33264989a94c0ba6d37b7e181f9713b14558e4d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
