name = "Sickos"
author = "brooswit"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11f7d1381e50fc64bdc752204040df81c187c0697507ce75e811a2d84c1e6445"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
