name = "Sickos"
author = "brooswit"
version = "0.25.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4414bb118fd01dd07a5cf51c1e416b65e3179ae8e930e4795fa3da56ccaee0df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
