name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    uses: brooswit-minecraft/schematic/.github/workflows/reusable-ci.yml@v1
    secrets: inherit
